### ISSUE TITLE
[Feature]: Migrate to TF Plugin Framework

### ISSUE THREAD

**Issue by apricote** [hetznercloud/terraform-provider-hcloud#752]
### What whould you like to see?

Terraform has launched a new "Plugin Framework" that replaces the Plugin SDK v2. This new framework supports some advanced scenarios that currently do not work properly. It can help us solve a number of bugs that we are experiencing:

- SDK v2 only supports "int" while Plugin Framework supports explicit "int64" types (Related to [hcloud-go v2](https://github.com/hetznercloud/hcloud-go/releases/tag/v2.0.0), #997, #877)
- Plugin Framework supports strongly typed access to fields, which will help with a number of issues I discovered while trying to migrate to hcloud-go v2
- Terraform 1.4 introduced a bug for nested sets with computed fields (https://github.com/hetznercloud/terraform-provider-hcloud/issues/650). This would be fixed by switching to Plugin Framework
- Plugin Framework has a number of util functions regarding Diagnostics (https://github.com/hetznercloud/terraform-provider-hcloud/issues/692) that make them easier to use.
- SDK v2 only supports binary `ForceNew` for schema attributes. For `hcloud_server.server_type` it makes sense to `ForceNew` when switching between x86 and Arm, but to keep the same server and scale it in case the architecture stays the same. This is supported by the Plugin Framework. See #853
- For `hcloud_server.public_net` we have some bugs that are caused by the "Set" type for this argument. These can only be fixed in the Plugin Framework. See https://github.com/hetznercloud/terraform-provider-hcloud/issues/944 and https://github.com/hetznercloud/terraform-provider-hcloud/pull/597#issuecomment-2328321946

This migration will be a huge refactoring effort. We plan on doing it in many smaller steps, migrating a couple of resources at a time.

- [x] #749
- [ ] Migrate individual resources/datasources
  - [ ] Certificates
    - [ ] `hcloud_certificate`
    - [ ] `hcloud_uploaded_certificate`
    - [ ] `hcloud_managed_certificate`
    - [ ] `data.hcloud_certificate`
    - [ ] `data.hcloud_certificates`
  - [x] Datacenter
    - [x] `data.hcloud_datacenter` #779
    - [x] `data.hcloud_datacenters` #779
  - [ ] Firewall
    - [ ] `hcloud_firewall`
    - [ ] `hcloud_firewall_attachment`
    - [ ] `data.hcloud_firewall`
    - [ ] `data.hcloud_firewalls`
  - [ ] Floating IPs
    - [ ] `hcloud_floating_ip`
    - [ ] `hcloud_floating_ip_assignment`
    - [ ] `data.hcloud_floating_ip`
    - [ ] `data.hcloud_floating_ips`
  - [ ] Image
    - [ ] `data.hcloud_image`
    - [ ]  `data.hcloud_images`
  - [ ] Load Balancer
    - [ ] `hcloud_load_balancer`
    - [x] `hcloud_load_balancer_network` https://github.com/hetznercloud/terraform-provider-hcloud/pull/1246
    - [ ] `hcloud_load_balancer_service`
    - [ ] `hcloud_load_balancer_target`
    - [ ] `data.hcloud_load_balancer`
    - [ ] `data.hcloud_load_balancers`
  - [x] Location
    - [x] `data.hcloud_location` https://github.com/hetznercloud/terraform-provider-hcloud/pull/796
    - [x] `data.hcloud_locations` https://github.com/hetznercloud/terraform-provider-hcloud/pull/796
  - [ ] Network
    - [ ] `hcloud_network`
    - [ ] `hcloud_network_subnet`
    - [ ] `hcloud_network_route`
    - [ ] `data.hcloud_network`
    - [ ] `data.hcloud_networks`
  - [ ] Placement Group
    - [ ] `hcloud_placement_group`
    - [ ] `data.hcloud_placement_group`
    - [ ] `data.hcloud_placement_groups`
  - [x] Primary IP
    - [x] `hcloud_primary_ip` https://github.com/hetznercloud/terraform-provider-hcloud/pull/1385
    - [x] `data.hcloud_primary_ip` https://github.com/hetznercloud/terraform-provider-hcloud/pull/1385
    - [x] `data.hcloud_primary_ips` https://github.com/hetznercloud/terraform-provider-hcloud/pull/1385
  - [x] RDNS
    - [x] `hcloud_rdns` https://github.com/hetznercloud/terraform-provider-hcloud/pull/1419
  - [ ] Server
    - [ ] `hcloud_server`
    - [x] `hcloud_server_network` https://github.com/hetznercloud/terraform-provider-hcloud/pull/1244
    - [ ] `data.hcloud_server`
    - [ ] `data.hcloud_servers`
  - [x] Server Type
    - [x] `data.hcloud_server_type` https://github.com/hetznercloud/terraform-provider-hcloud/pull/959
    - [x] `data.hcloud_server_types` https://github.com/hetznercloud/terraform-provider-hcloud/pull/959
  - [ ] Snapshot
    - [ ] `hcloud_snapshot`
  - [x] SSH Key
    - [x] `hcloud_ssh_key` #817 
    - [x] `data.hcloud_ssh_key` #817 
    - [x] `data.hcloud_ssh_keys` #817 
  - [ ] Volume
    - [ ] `hcloud_volume`
    - [ ] `hcloud_volume_attachment`
    - [ ] `data.hcloud_volume`
    - [ ] `data.hcloud_volumes`
- [ ] Clean up remaining SDK v2 usages
- [ ] Clean up old provider & muxing

**Comment by jooola** [comment]
The following data sources and resources will very likely have breaking changes when migrated to the Plugin Framework:

```
internal/firewall/resource.go:59                .apply_to
internal/firewall/resource.go:77                .rule
internal/loadbalancer/data_source.go:           "A lot of deeply nested List|Set type, that might break"
internal/loadbalancer/resource.go:97            .algorithm
internal/loadbalancer/resource.go:127           .target (deprecated for 5 years)
internal/loadbalancer/resource_service.go:75    .http
internal/loadbalancer/resource_service.go:119   .health_check
internal/loadbalancer/resource_service.go:151   .health_check.http
internal/server/resource.go:178                 .public_net
internal/server/resource.go:212                 .network
```

The list above shows the resource with a nested block in them. Those nested block are usually implement at `List` or `Set` in the SDK, with a `Elem: &schema.Resource` as element type.

It does not seem possible to migrate those nested blocks to the plugin framework without introducing a breaking change. Part of the issue is explained in https://github.com/hashicorp/terraform-plugin-framework/issues/883.

If the nested object is exclusively `Computed`, migrating to the Plugin framework is not an issue. It is when user can provide an `Optional` configuration. Also, when the block is not read from (only `Optional` and not `Computed`), we might be able to still migrate without breaking change. 

Therefor, I recommend to focus on all the other resources data sources, and prepare a major release for those last resources that will require this breaking change.
